<!doctype html>
<html lang="ru" class="no-js">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{{root}}/assets/css/pure.css"> <!-- Ask Form style -->
    <link rel="stylesheet" href="{{root}}/assets/css/reset.css"> <!-- CSS reset -->

    <link rel="stylesheet" href="{{root}}/assets/css/style.css"> <!-- Resource style -->
    <script src="{{root}}/assets/js/modernizr.js"></script> <!-- Modernizr -->
    <title>Админка</title>
</head>
<body>
<header>
    <h1>Вопросы и Ответы</h1>
</header>
<section class="cd-faq">
    {% if admin %}
    <ul class="cd-faq-categories">
        <li>Администраторы</li>
        <li><a href="{{'admin'|buildHref}}" data-noa="noa">Список Администраторов</a></li>
        <li><a href="{{'admin/new'|buildHref}}" data-noa="noa">Создать администратора</a></li>
        <li><a href="{{'admin/edit'|buildHref}}" data-noa="noa">Редактировать администратора</a></li>
        <li><a href="{{'admin/del'|buildHref}}" data-noa="noa">Удалить администратора</a></li>
        <li>Категории</li>
        <li><a href="{{'cat/new'|buildHref}}" data-noa="noa">Создать тему</a></li>
        <li><a href="{{'cat/del'|buildHref}}" data-noa="noa">Удалить тему</a></li>
        <li>Вопросы</li>
        <li><a href="{{'ask'|buildHref}}" data-noa="noa">Задать вопрос</a></li>
        <li><a href="{{'cat/view'|buildHref}}" data-noa="noa">Редактировать вопросы</a></li>
        <li><a href="{{'q/list'|buildHref}}" data-noa="noa">Список без ответов</a></li>
        <li><a href="{{'q/blist'|buildHref}}" data-noa="noa">Заблокированные</a></li>
        <li><a href="{{'q/bot'|buildHref}}" data-noa="noa">Вопросы Telegram</a></li>
        <li>Стопслова</li>
        <li><a href="{{'sw/list'|buildHref}}" data-noa="noa">Список слов</a></li>
        <li><a href="{{'sw/new'|buildHref}}" data-noa="noa">Добавить слово</a></li>
        <li><a href="{{'sw/del'|buildHref}}" data-noa="noa">Удалить слово</a></li>
        <li>Аккаунт</li>
        <li><a href="{{'Index'|buildHref}}" data-noa="noa">На главную</a></li>
        <li><a href="{{'admin/logout'|buildHref}}" data-noa="noa">Выйти</a></li>
    </ul> <!-- cd-faq-categories -->
    {% else %}
    <ul class="cd-faq-categories">
        <li><a href="#">Войти</a></li>
        <li><a href="{{'Index'|buildHref}}" data-noa="noa">На главную</a></li>
    </ul>
    {% endif %}
    <div class="cd-faq-items">
    {% block content %}{% endblock %}
    <a href="#0" class="cd-close-panel">Close</a>
    </div>
</section> <!-- cd-faq -->
<script src="{{root}}/assets/js/jquery-2.1.1.js"></script>
<script src="{{root}}/assets/js/jquery.mobile.custom.min.js"></script>
{% if not admin %}
<script src="{{root}}/assets/js/main.js"></script> <!-- Resource jQuery -->
{% endif %}
</body>
</html>