{% extends 'layout.phtml' %}

{% block content %}

<form action="{{'ask'|buildHref}}" method="post" class="pure-form pure-form-aligned">
    <fieldset>
        <legend>Задайте свой вопрос</legend>

        <div class="pure-control-group">
            <label for="name">Имя</label>
            <input id="name" type="text" name="ask[name]"
                   placeholder="Ваше имя" required class="pure-input-1-2">
        </div>

        <div class="pure-control-group">
            <label for="email">Email</label>
            <input id="email" type="email" name="ask[email]"
                   placeholder="Email" required class="pure-input-1-2">
        </div>

        <div class="pure-control-group">
            <label for="category">Категория</label>
            <select id="category" class="pure-input-1-3" name="ask[category]">
                {% for cat in cats %}
                <option value="{{cat.id}}">{{cat.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="pure-control-group">
            <label for="title">Заголовок вопроса</label>
            <input id="title" type="text" name="ask[title]"
                   placeholder="Заголовок вопроса" required class="pure-input-1-2">
        </div>

        <div class="pure-control-group">
            <label for="question">Вопрос</label>
            <textarea id="question" rows="5"  name="ask[question]"
                      placeholder="Ваш вопрос" required class="pure-input-1-2"></textarea>
        </div>

        <div class="pure-controls">
            <button type="submit" class="pure-button button-success">Задать вопрос</button>
        </div>
    </fieldset>
</form>
{% endblock %}