{% extends 'layout.phtml' %}

{% block content %}
<ul class="cd-faq-categories">
    {% for cat in cats %}
    {% if loop.first %}
    <li><a class="selected" href="#{{cat.slug}}">{{cat.name}}</a></li>
    {% else %}
    <li><a href="#{{cat.slug}}">{{cat.name}}</a></li>
    {% endif %}
    {% endfor %}
</ul> <!-- cd-faq-categories -->
<div class="cd-faq-items">
    <div class="pure-menu pure-menu-horizontal"><ul class="pure-menu-list">
        <li class="pure-menu-item"><a class="pure-menu-link" href="{{'admin'|buildHref}}">{{ admin ? 'В админку' : 'Войти' }}</a></li>
        <li class="pure-menu-item"><a class="pure-menu-link" href="{{'ask'|buildHref}}">Задать вопрос</a></li>
        </ul>
    </div>
    {% for cat in cats %}
    <ul id="{{cat.slug}}" class="cd-faq-group">
        <li class="cd-faq-title"><h2>{{cat.name}}</h2></li>
        {% if cat.questions is not empty %}
        {% for question in cat.questions %}
        <li>
            <a class="cd-faq-trigger" href="#0">{{question.q}}</a>
            <div class="cd-faq-content">
                <div class="answer">
                    <p><strong>Ответ: </strong>{{question.a}}</p>
                </div>
            </div> <!-- cd-faq-content -->
        </li>
        {% endfor %}
        {% else %}
        <li class="nocontent"><p >В данной категории нет вопросов. Вы можете <a href="{{'ask'|buildHref}}">задать</a> его.</p></li>
        {% endif %}
    </ul>
    {% endfor %}
</div> <!-- cd-faq-items -->
<a href="#0" class="cd-close-panel">Close</a>
{% endblock %}