<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Вопросы и Ответы | netology</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body class="container">
    <div class="jumbotron">
        <h1>QA сервис</h1>
        <p>лучший сервис вопросов и ответов</p>
    </div>
    {{content}}
    <ul>
    {% for item in items %}
    <li>{{ item.description }}</li>
    {% endfor %}
    </ul>
</body>
</html>