<!doctype html>
<html lang="ru" class="no-js">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="assets/css/pure.css"> <!-- Ask Form style -->
    <link rel="stylesheet" href="assets/css/reset.css"> <!-- CSS reset -->

    <link rel="stylesheet" href="assets/css/style.css"> <!-- Resource style -->
    <script src="assets/js/modernizr.js"></script> <!-- Modernizr -->
    <title>Сервис Вопросв и Ответов</title>
</head>
<body>
<header>
    <h1>Вопросы и Ответы</h1>
</header>
<section class="cd-faq">
    {% block content %}{% endblock %}
</section> <!-- cd-faq -->
<script src="assets/js/jquery-2.1.1.js"></script>
<script src="assets/js/jquery.mobile.custom.min.js"></script>
<script src="assets/js/main.js"></script> <!-- Resource jQuery -->
</body>
</html>