{% extends 'alayout.phtml' %}

{% block content %}
<form action="{{'sw/new'|buildHref}}" method="post" class="pure-form pure-form-aligned">
    <fieldset>
        <legend>Добавить слово</legend>

        <div class="pure-control-group">
            <label for="word">слово</label>
            <input id="word" type="text" name="word"
                   placeholder="слово для блокировки" required class="pure-input-1-2">
        </div>

        <div class="pure-controls">
            <button type="submit" class="pure-button button-success">добавить</button>
        </div>
    </fieldset>
</form>
{% endblock %}